---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: test-knative-serving
  namespace: default
spec:
  interval: 5m
  url: https://github.com/mbrancato/test-knative-serving
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test-knative-serving
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: test-knative-serving
  path: "./knative-serving"
  prune: true
